### ISSUE TITLE
Feature: Dockerimage

### ISSUE THREAD

**Issue by itsezc** [surrealdb/surrealkv#56]
Since SurrealKV is ready for usage (as beta) with SurrealDB, it'd be useful to have a Dockerimage and have it published on Docker hub

**Comment by arriqaaq** [comment]
Hi @itsezc 

surrealkv is en embedded database, like rocksdb/sled/redb. The docker/helm image will not really help at all. You can always embed it in your application like a crate.

If you want to use it with surrealdb with the existing docker image, you can always use our existing docker commands to use surrealkv from the beta image

```docker run --rm --pull always -p 8000:8000 --user $(id -u) -v $(pwd)/mydata:/mydata surrealdb/surrealdb:latest start surrealkv:/mydata/mydatabase.db```

**Comment by Sandros94** [comment]
> If you want to use it with surrealdb with the existing docker image, you can always use our existing docker commands to use surrealkv from the beta image
> 
> `docker run --rm --pull always -p 8000:8000 --user $(id -u) -v $(pwd)/mydata:/mydata surrealdb/surrealdb:latest start surrealkv:/mydata/mydatabase.db`

I might be missing something but you were referring to a _"beta image"_ while the docker run is referring to the latest tag. Is this correct?

**Comment by itsezc** [comment]
> > If you want to use it with surrealdb with the existing docker image, you can always use our existing docker commands to use surrealkv from the beta image
> > `docker run --rm --pull always -p 8000:8000 --user $(id -u) -v $(pwd)/mydata:/mydata surrealdb/surrealdb:latest start surrealkv:/mydata/mydatabase.db`
> 
> I might be missing something but you were referring to a _"beta image"_ while the docker run is referring to the latest tag. Is this correct?

There is no tag for `beta` or `v2` for Surreal, the closest you have according to [Dockerhub](https://hub.docker.com/r/surrealdb/surrealdb/tags) would be `nightly` or [v2.0.0-alpha.7-dev](https://hub.docker.com/layers/surrealdb/surrealdb/v2.0.0-alpha.7-dev/images/sha256-42af280f72060162659a52457555b81bf04148101e1be8ab120a3d5d777bc44d?context=explore) which is current alpha for v2.

**Comment by arriqaaq** [comment]
Hey @itsezc 

You are right, thanks for correcting. The nightly would be the one
