### ISSUE TITLE
This is not `chore:` is a `feat:`

### ISSUE THREAD

**Issue by Miuler** [surrealdb/surrealkv#6]
This is not `chore:` is a `feat:`

> chore: updating grunt tasks etc; no production code change

I am seeing that in all commits they are using `chore`, which confused me since this is used for things like ci, tasks in makefiles or cargo make, but not to modify code. Even angular stopped using `chore:` to use other things like `ci:` among others.

Please stop using chore, it is not suitable for these commits that modify the code.

- https://medium.com/neudesic-innovation/conventional-commits-a-better-way-78d6785c2e08
- https://stackoverflow.com/questions/26944762/when-to-use-chore-as-type-of-commit-message
- https://github.com/angular/angular/commit/dff6ee32725197bdb81f3f63c5bd9805f2ed22bb#diff-6a3371457528722a734f3c51d9238c13

**Comment by arriqaaq** [comment]
Hi @Miuler 

Thanks for raising concern about commit messages. We squash commits on merge with a "feat" message, following conventional Commits. While "chore" may seem unconventional, it serves its purpose during development.

But I notice that this wasn't used for the initial PR. Will rectify it. Thanks for catching it.

**Comment by Miuler** [comment]
In the add-store branch, the commit message is not correct:

![image](https://github.com/surrealdb/surrealkv/assets/9974/57a2d511-8ae8-40fc-8805-2c8da71fd2b0)

![image](https://github.com/surrealdb/surrealkv/assets/9974/1b327d75-e1fb-46e7-bd45-42f637fd849e)

**Comment by Miuler** [comment]
mmm... ok, although it would be a great squash
