### ISSUE TITLE
Savepoints features

### ISSUE THREAD

**Issue by emmanuel-keller** [surrealdb/surrealkv#74]
The savepoint feature is a mechanism that allows developers to create a point in a transaction.
It provides a way to rollback to this point.
Several savepoints can be created.
Rollback would restore the last created savepoints.

```
-> put X = 0
-> SetSavePoint() 
-> put Y= 1
-> SetSavePoint()
-> set X = 2
-> RollbackToSavePoint() = restore X to 0
-> put Z
-> Rollbackto SavePoint() = remove Y and Z
```

**Comment by arriqaaq** [comment]
Resolved in [this](https://github.com/surrealdb/surrealkv/pull/75) PR
